import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// Import Google Fonts (server-side)
const geistSans = Geist({
  subsets: ["latin"],
  variable: "--font-geist-sans",
});

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-geist-mono",
});

// Metadata for your layout (server-side only)
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout must not include "use client"
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
      </body>
    </html>
  );
}
